name: onboarding_flutter_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  pinput: ^5.0.0
  share_plus: ^9.0.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  flutter_form_builder: ^9.2.1
  provider: ^6.1.2
  stepper_page_view: ^0.0.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/

  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        
  
  
  
